import { amountToIndianWords } from './calculations.ts';

const todayStr = new Date().toISOString().slice(0, 10);

export const INITIAL_WORKSPACE_DATA = {
  currentUser: {
    id: 1,
    uid: 'nrd_owner_uid',
    name: 'Farooq Royal (Proprietor)',
    email: 'info@newroyaldecorators.in',
    role: 'Admin',
    phone: '+91 98230 45112',
    active: true,
  },
  users: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      name: 'Farooq Royal (Proprietor)',
      email: 'info@newroyaldecorators.in',
      role: 'Admin',
      phone: '+91 98230 45112',
      active: true,
    },
    {
      id: 2,
      uid: 'staff_manager_1',
      name: 'Rizwan Khan',
      email: 'rizwan@newroyaldecorators.in',
      role: 'Manager',
      phone: '+91 97654 32109',
      active: true,
    },
    {
      id: 3,
      uid: 'staff_site_1',
      name: 'Imran Shaikh (Site Supervisor)',
      email: 'imran.site@newroyaldecorators.in',
      role: 'Site Staff',
      phone: '+91 98234 01190',
      active: true,
    },
    {
      id: 4,
      uid: 'staff_billing_1',
      name: 'Sneha Kulkarni',
      email: 'billing@newroyaldecorators.in',
      role: 'Billing Staff',
      phone: '+91 98501 22334',
      active: true,
    },
    {
      id: 5,
      uid: 'staff_ca_1',
      name: 'CA Pradeep Joshi',
      email: 'accounts@newroyaldecorators.in',
      role: 'Accountant',
      phone: '+91 94220 88776',
      active: true,
    },
  ],
  business: {
    id: 1,
    uid: 'nrd_owner_uid',
    businessName: 'NEW ROYAL DECORATORS',
    category:
      'False Ceiling Works, PVC Ceiling, Gypsum Board, POP Work, Flower & Border Fitting, Interior Decoration.',
    logoUrl: '',
    address: 'Shop No. 14, Timber Market Road, Near Royal Chowk, Pune - 411002',
    mobileNumbers: '+91 98230 45112, +91 97654 32109',
    email: 'info@newroyaldecorators.in',
    gstin: '27AABCN1234F1Z5',
    pan: 'AABCN1234F',
    state: 'Maharashtra',
    stateCode: '27',
    bankName: 'HDFC Bank Ltd.',
    accountName: 'NEW ROYAL DECORATORS',
    accountNumber: '50200048291044',
    ifscCode: 'HDFC0000142',
    branch: 'Station Road Branch, Pune',
    upiId: 'newroyaldecorators@hdfcbank',
    invoicePrefix: 'NRD/26-27/INV-',
    quotationPrefix: 'NRD/26-27/QTN-',
    measurementPrefix: 'NRD/26-27/MS-',
    bomPrefix: 'NRD/26-27/BOM-',
    receiptPrefix: 'NRD/26-27/RCP-',
    defaultGstRate: '18.00',
    termsAndConditions:
      '1. 50% advance payment at the time of order confirmation.\n2. 30% running payment after GI framework & board/panel structure completion.\n3. Balance 20% strictly upon completion of work before site handover.\n4. Scaffolding, electricity, and water at site to be provided by the customer.\n5. Extra work beyond quotation will be billed per actual site measurement.\n6. Subject to local jurisdiction only.',
  },
  customers: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      name: 'Rajeshwar Deshmukh',
      mobile: '9822114455',
      email: 'rajeshwar.deshmukh@gmail.com',
      address: 'Plot 18, Mayur Colony, Kothrud, Pune - 411038',
      gstin: '27AALPD4821M1Z2',
      pan: 'AALPD4821M',
      state: 'Maharashtra',
      stateCode: '27',
      siteAddress: 'Royal Bunglow No. 7, Prabhat Road, Deccan, Pune',
      openingBalance: '0.00',
      createdBy: 'Admin',
      updatedBy: 'Admin',
    },
    {
      id: 2,
      uid: 'nrd_owner_uid',
      name: 'Shriram Spaces & Developers Pvt. Ltd.',
      mobile: '9765008811',
      email: 'projects@shriramspaces.in',
      address: '402, Elite Business Park, Baner High Street, Pune - 411045',
      gstin: '27AAHCS9102K1Z8',
      pan: 'AAHCS9102K',
      state: 'Maharashtra',
      stateCode: '27',
      siteAddress: 'Shriram Commercial Arcade, Balewadi Phata, Pune',
      openingBalance: '0.00',
      createdBy: 'Admin',
      updatedBy: 'Admin',
    },
    {
      id: 3,
      uid: 'nrd_owner_uid',
      name: 'Metro Suites & Hospitality LLP',
      mobile: '9900442210',
      email: 'procurement@metrosuites.co.in',
      address: 'MG Road, Indiranagar, Bengaluru - 560038',
      gstin: '29AABFM7721E1Z4',
      pan: 'AABFM7721E',
      state: 'Karnataka',
      stateCode: '29',
      siteAddress: 'Metro Boutique Hotel, Belagavi Highway Wing',
      openingBalance: '0.00',
      createdBy: 'Admin',
      updatedBy: 'Admin',
    },
  ],
  projects: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      projectName: 'Deshmukh Duplex Bungalow - Full PVC & POP Ceiling',
      customerId: 1,
      siteAddress: 'Royal Bunglow No. 7, Prabhat Road, Deccan, Pune',
      startDate: '2026-09-25',
      expectedCompletionDate: '2026-10-18',
      status: 'Partially Paid',
      notes:
        'Ground floor + First floor bedrooms PVC ceiling, Hall gypsum cove ceiling, and exterior site fascia.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
    },
    {
      id: 2,
      uid: 'nrd_owner_uid',
      projectName: 'Shriram Commercial Showroom - Gypsum Grid & Cove',
      customerId: 2,
      siteAddress: 'Shriram Commercial Arcade, Balewadi Phata, Pune',
      startDate: '2026-09-28',
      expectedCompletionDate: '2026-10-25',
      status: 'Work Started',
      notes: 'Double layer Saint-Gobain gypsum ceiling with 15W COB LED cutout provision.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
    },
    {
      id: 3,
      uid: 'nrd_owner_uid',
      projectName: 'Metro Suites Banquet Hall - POP Flower & Golden Border',
      customerId: 3,
      siteAddress: 'Metro Boutique Hotel, Belagavi Highway Wing',
      startDate: '2026-10-01',
      expectedCompletionDate: '2026-11-05',
      status: 'Quotation',
      notes: 'Inter-state project (IGST 18%). Ornamental POP cornice and 6 ceiling medallions.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
    },
  ],
  sites: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      projectId: 1,
      customerId: 1,
      siteName: 'Deshmukh Duplex - Prabhat Road Site',
      siteAddress: 'Royal Bunglow No. 7, Prabhat Road, Deccan, Pune',
      supervisorName: 'Imran Shaikh',
      supervisorMobile: '9823401190',
      floors: 'Ground Floor, First Floor, Site Fascia',
    },
  ],
  products: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      name: 'Heavy PVC Ceiling Panel 10" x 10ft (Royal Teak)',
      sku: 'NRD-PVC-001',
      category: 'PVC Ceiling',
      brand: 'Royal Plast',
      hsnSac: '3925',
      unit: 'sq.ft',
      purchasePrice: '38.00',
      sellingPrice: '65.00',
      gstRate: '18.00',
      stockQuantity: '2400.00',
      minStockLevel: '500.00',
    },
    {
      id: 2,
      uid: 'nrd_owner_uid',
      name: 'Saint-Gobain Gyproc Standard Board 12.5mm (6x4 ft)',
      sku: 'NRD-GYP-002',
      category: 'Gypsum Ceiling',
      brand: 'Saint-Gobain Gyproc',
      hsnSac: '6809',
      unit: 'sq.ft',
      purchasePrice: '42.00',
      sellingPrice: '75.00',
      gstRate: '18.00',
      stockQuantity: '1800.00',
      minStockLevel: '400.00',
    },
    {
      id: 3,
      uid: 'nrd_owner_uid',
      name: 'Sakarni Super White POP Plaster (25kg Bag)',
      sku: 'NRD-POP-003',
      category: 'POP Ceiling',
      brand: 'Sakarni',
      hsnSac: '2520',
      unit: 'box',
      purchasePrice: '195.00',
      sellingPrice: '280.00',
      gstRate: '18.00',
      stockQuantity: '85.00',
      minStockLevel: '20.00',
    },
    {
      id: 4,
      uid: 'nrd_owner_uid',
      name: 'Ultra Gyp GI Perimeter Channel 0.55mm (12ft)',
      sku: 'NRD-GI-004',
      category: 'GI Framework',
      brand: 'Ultra Gyp',
      hsnSac: '7308',
      unit: 'piece',
      purchasePrice: '115.00',
      sellingPrice: '165.00',
      gstRate: '18.00',
      stockQuantity: '320.00',
      minStockLevel: '50.00',
    },
    {
      id: 5,
      uid: 'nrd_owner_uid',
      name: 'Ultra Gyp GI Ceiling Section 0.55mm (12ft)',
      sku: 'NRD-GI-005',
      category: 'GI Framework',
      brand: 'Ultra Gyp',
      hsnSac: '7308',
      unit: 'piece',
      purchasePrice: '145.00',
      sellingPrice: '210.00',
      gstRate: '18.00',
      stockQuantity: '290.00',
      minStockLevel: '50.00',
    },
    {
      id: 6,
      uid: 'nrd_owner_uid',
      name: 'POP Ornamental Cornice & Border Moulding',
      sku: 'NRD-DEC-006',
      category: 'Interior Decoration',
      brand: 'New Royal Custom',
      hsnSac: '6809',
      unit: 'running feet',
      purchasePrice: '28.00',
      sellingPrice: '55.00',
      gstRate: '18.00',
      stockQuantity: '950.00',
      minStockLevel: '150.00',
    },
    {
      id: 7,
      uid: 'nrd_owner_uid',
      name: 'POP Central Ceiling Medallion Flower (36 inch)',
      sku: 'NRD-DEC-007',
      category: 'Interior Decoration',
      brand: 'New Royal Custom',
      hsnSac: '6809',
      unit: 'piece',
      purchasePrice: '450.00',
      sellingPrice: '950.00',
      gstRate: '18.00',
      stockQuantity: '24.00',
      minStockLevel: '5.00',
    },
    {
      id: 8,
      uid: 'nrd_owner_uid',
      name: '15W Warm White Concealed LED Panel Light + Cove Strip',
      sku: 'NRD-LGT-008',
      category: 'Lighting',
      brand: 'Philips',
      hsnSac: '9405',
      unit: 'piece',
      purchasePrice: '310.00',
      sellingPrice: '480.00',
      gstRate: '18.00',
      stockQuantity: '110.00',
      minStockLevel: '25.00',
    },
    {
      id: 9,
      uid: 'nrd_owner_uid',
      name: 'High-Carbon Drywall Star Screws 25mm (1000 pcs Box)',
      sku: 'NRD-HRD-009',
      category: 'Hardware',
      brand: 'Hilti / Grip',
      hsnSac: '7318',
      unit: 'box',
      purchasePrice: '240.00',
      sellingPrice: '360.00',
      gstRate: '18.00',
      stockQuantity: '18.00',
      minStockLevel: '5.00',
    },
    {
      id: 10,
      uid: 'nrd_owner_uid',
      name: 'Skilled False Ceiling & POP Installation Labour',
      sku: 'NRD-LAB-010',
      category: 'False Ceiling',
      brand: 'NRD In-House Team',
      hsnSac: '9954',
      unit: 'sq.ft',
      purchasePrice: '22.00',
      sellingPrice: '35.00',
      gstRate: '18.00',
      stockQuantity: '9999.00',
      minStockLevel: '0.00',
    },
  ],
  measurements: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      measurementNumber: 'NRD/26-27/MS-001',
      date: '2026-10-01',
      customerId: 1,
      projectId: 1,
      siteName: 'Royal Bunglow No. 7, Prabhat Road, Deccan, Pune',
      totalAreaSqft: '647.00',
      pvcCeilingSqft: '448.00',
      popCeilingSqft: '199.00',
      gypsumCeilingSqft: '0.00',
      materialEstimate: '36420.00',
      labourEstimate: '18535.00',
      otherCharges: '2500.00',
      discount: '1455.00',
      gstRate: '18.00',
      gstAmount: '10080.00',
      grandTotal: '66080.00',
      notes:
        'Handwritten site sheet digitized: Ground Floor Bed Room, First Floor Rooms, and Exterior Site Fascia.',
      createdBy: 'Imran Shaikh (Site Supervisor)',
      updatedBy: 'Farooq Royal (Proprietor)',
      items: [
        {
          id: 1,
          measurementId: 1,
          section: 'Ground Floor',
          room: 'Bed Room',
          workType: 'PVC Ceiling',
          description: 'Master Bed Room Teak Wood Finish PVC Panel',
          rawExpression: '14 x 11',
          lengthInput: '14',
          widthInput: '11',
          lengthFeet: '14.0000',
          widthFeet: '11.0000',
          quantity: '1.00',
          calcType: 'SQFT',
          areaSqft: '154.00',
          rate: '85.00',
          amount: '13090.00',
        },
        {
          id: 2,
          measurementId: 1,
          section: 'Ground Floor',
          room: 'Hall Passage',
          workType: 'PVC Ceiling',
          description: 'Living Room & Passage Heavy PVC Ceiling',
          rawExpression: '28 x 5',
          lengthInput: '28',
          widthInput: '5',
          lengthFeet: '28.0000',
          widthFeet: '5.0000',
          quantity: '1.00',
          calcType: 'SQFT',
          areaSqft: '140.00',
          rate: '85.00',
          amount: '11900.00',
        },
        {
          id: 3,
          measurementId: 1,
          section: 'First Floor',
          room: 'Bed Room 2',
          workType: 'PVC Ceiling',
          description: 'First Floor Master Bed Room PVC Ceiling',
          rawExpression: '14 x 11',
          lengthInput: '14',
          widthInput: '11',
          lengthFeet: '14.0000',
          widthFeet: '11.0000',
          quantity: '1.00',
          calcType: 'SQFT',
          areaSqft: '154.00',
          rate: '85.00',
          amount: '13090.00',
        },
        {
          id: 4,
          measurementId: 1,
          section: 'First Floor',
          room: 'Balcony Lobby',
          workType: 'POP Ceiling',
          description: 'First Floor Lobby POP Ceiling with Cove Border',
          rawExpression: '11 x 4',
          lengthInput: '11',
          widthInput: '4',
          lengthFeet: '11.0000',
          widthFeet: '4.0000',
          quantity: '1.00',
          calcType: 'SQFT',
          areaSqft: '44.00',
          rate: '90.00',
          amount: '3960.00',
        },
        {
          id: 5,
          measurementId: 1,
          section: 'First Floor',
          room: 'Pooja & Dressing',
          workType: 'POP Ceiling',
          description: 'Pooja Room Ornamental POP & Flower Fitting',
          rawExpression: '8 x 4',
          lengthInput: '8',
          widthInput: '4',
          lengthFeet: '8.0000',
          widthFeet: '4.0000',
          quantity: '1.00',
          calcType: 'SQFT',
          areaSqft: '32.00',
          rate: '90.00',
          amount: '2880.00',
        },
        {
          id: 6,
          measurementId: 1,
          section: 'Site Fascia',
          room: 'Front Fascia Left',
          workType: 'POP Ceiling',
          description: 'Front Elevation Fascia Drop 3ft 6in',
          rawExpression: '10 x 3\'6"',
          lengthInput: '10',
          widthInput: '3\'6"',
          lengthFeet: '10.0000',
          widthFeet: '3.5000',
          quantity: '1.00',
          calcType: 'SQFT',
          areaSqft: '35.00',
          rate: '80.00',
          amount: '2800.00',
        },
        {
          id: 7,
          measurementId: 1,
          section: 'Site Fascia',
          room: 'Main Porch Fascia',
          workType: 'POP Ceiling',
          description: 'Main Entrance Canopy Fascia 16ft x 5ft 6in',
          rawExpression: '16 x 5\'6"',
          lengthInput: '16',
          widthInput: '5\'6"',
          lengthFeet: '16.0000',
          widthFeet: '5.5000',
          quantity: '1.00',
          calcType: 'SQFT',
          areaSqft: '88.00',
          rate: '82.00',
          amount: '7216.00',
        },
      ],
    },
  ],
  boms: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      bomNumber: 'NRD/26-27/BOM-001',
      date: '2026-10-01',
      customerId: 1,
      projectId: 1,
      measurementId: 1,
      totalMaterialCost: '34860.00',
      totalLabourCost: '16450.00',
      grandTotal: '51310.00',
      notes: 'Generated automatically from Measurement Sheet NRD/26-27/MS-001 with 5% material wastage.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      items: [
        {
          id: 1,
          bomId: 1,
          productId: 1,
          itemName: 'Heavy PVC Ceiling Panel 10" x 10ft (Royal Teak)',
          category: 'PVC Ceiling',
          brand: 'Royal Plast',
          specification: '10 inch width x 10 ft length, 8mm heavy gauge',
          hsnSac: '3925',
          unit: 'sq.ft',
          requiredQty: '448.00',
          wastagePercent: '5.00',
          finalQty: '470.40',
          purchaseRate: '38.00',
          sellingRate: '50.00',
          materialCost: '23520.00',
          labourCost: '11200.00',
          total: '34720.00',
        },
        {
          id: 2,
          bomId: 1,
          productId: 3,
          itemName: 'Sakarni Super White POP Plaster (25kg Bag)',
          category: 'POP Ceiling',
          brand: 'Sakarni',
          specification: 'Super fine grade for 199 sq.ft POP ceiling & fascia',
          hsnSac: '2520',
          unit: 'box',
          requiredQty: '12.00',
          wastagePercent: '5.00',
          finalQty: '13.00',
          purchaseRate: '195.00',
          sellingRate: '280.00',
          materialCost: '3640.00',
          labourCost: '3250.00',
          total: '6890.00',
        },
        {
          id: 3,
          bomId: 1,
          productId: 4,
          itemName: 'Ultra Gyp GI Perimeter & Ceiling Section Framework',
          category: 'GI Framework',
          brand: 'Ultra Gyp',
          specification: '0.55mm Zinc Coated GI Channels (12ft lengths)',
          hsnSac: '7308',
          unit: 'piece',
          requiredQty: '45.00',
          wastagePercent: '4.00',
          finalQty: '47.00',
          purchaseRate: '115.00',
          sellingRate: '163.83',
          materialCost: '7700.00',
          labourCost: '2000.00',
          total: '9700.00',
        },
      ],
    },
  ],
  quotations: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      quotationNumber: 'NRD/26-27/QTN-001',
      date: '2026-10-01',
      validUntil: '2026-10-16',
      customerId: 1,
      projectId: 1,
      measurementId: 1,
      bomId: 1,
      siteAddress: 'Royal Bunglow No. 7, Prabhat Road, Deccan, Pune',
      status: 'Converted',
      materialSubtotal: '38080.00',
      labourCost: '16856.00',
      otherCharges: '2500.00',
      subtotal: '57436.00',
      discount: '1436.00',
      taxableAmount: '56000.00',
      gstRate: '18.00',
      gstAmount: '10080.00',
      grandTotal: '66080.00',
      termsAndConditions:
        '1. 50% advance payment at the time of order confirmation.\n2. 30% running payment after GI framework & board/panel structure completion.\n3. Balance 20% strictly upon completion of work before site handover.\n4. Scaffolding, electricity, and water at site to be provided by the customer.',
      notes: 'Includes GI heavy gauge framing, Royal Plast PVC sheets, and Sakarni POP fascia work.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      items: [
        {
          id: 1,
          quotationId: 1,
          section: 'Ground & First Floor',
          description: 'Supply & Installation of Heavy PVC Ceiling with GI Framing (448 sq.ft)',
          hsnSac: '9954',
          quantity: '448.00',
          unit: 'sq.ft',
          rate: '85.00',
          amount: '38080.00',
        },
        {
          id: 2,
          quotationId: 1,
          section: 'First Floor & Site Fascia',
          description: 'Supply & Execution of Sakarni POP Ceiling, Cove & Fascia Work (199 sq.ft)',
          hsnSac: '9954',
          quantity: '199.00',
          unit: 'sq.ft',
          rate: '84.70',
          amount: '16856.00',
        },
        {
          id: 3,
          quotationId: 1,
          section: 'Site Accessories',
          description: 'POP Central Flower Medallion & LED Cutout Finishing',
          hsnSac: '9954',
          quantity: '1.00',
          unit: 'job',
          rate: '2500.00',
          amount: '2500.00',
        },
      ],
    },
    {
      id: 2,
      uid: 'nrd_owner_uid',
      quotationNumber: 'NRD/26-27/QTN-002',
      date: '2026-10-02',
      validUntil: '2026-10-20',
      customerId: 3,
      projectId: 3,
      measurementId: null,
      bomId: null,
      siteAddress: 'Metro Boutique Hotel, Belagavi Highway Wing',
      status: 'Pending',
      materialSubtotal: '62000.00',
      labourCost: '28000.00',
      otherCharges: '5000.00',
      subtotal: '95000.00',
      discount: '5000.00',
      taxableAmount: '90000.00',
      gstRate: '18.00',
      gstAmount: '16200.00',
      grandTotal: '106200.00',
      termsAndConditions:
        '1. 50% advance payment at the time of order confirmation.\n2. 30% running payment after GI framework & board/panel structure completion.\n3. Balance 20% strictly upon completion of work before site handover.',
      notes: 'Banquet Hall ornamental POP ceiling with golden border moulding.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      items: [
        {
          id: 4,
          quotationId: 2,
          section: 'Banquet Hall',
          description: 'Designer POP False Ceiling with Acoustic GI Grid (1000 sq.ft)',
          hsnSac: '9954',
          quantity: '1000.00',
          unit: 'sq.ft',
          rate: '95.00',
          amount: '95000.00',
        },
      ],
    },
  ],
  invoices: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      invoiceNumber: 'NRD/26-27/INV-001',
      invoiceDate: todayStr,
      dueDate: '2026-10-18',
      customerId: 1,
      projectId: 1,
      quotationId: 1,
      measurementId: 1,
      customerGstin: '27AALPD4821M1Z2',
      placeOfSupply: 'Maharashtra (27)',
      isInterState: false,
      subtotal: '57436.00',
      discount: '1436.00',
      taxableValue: '56000.00',
      gstRate: '18.00',
      cgstAmount: '5040.00',
      sgstAmount: '5040.00',
      igstAmount: '0.00',
      totalGst: '10080.00',
      grandTotal: '66080.00',
      amountPaid: '40000.00',
      balanceDue: '26080.00',
      amountInWords: amountToIndianWords(66080),
      status: 'Partially Paid',
      isFinalized: true,
      notes: '50%+ running payment received via UPI. Balance due upon site completion.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      items: [
        {
          id: 1,
          invoiceId: 1,
          description: 'PVC Ceiling Supply & Installation (Ground & First Floor - 448 sq.ft)',
          hsnSac: '9954',
          quantity: '448.00',
          unit: 'sq.ft',
          rate: '85.00',
          taxableValue: '38080.00',
          gstRate: '18.00',
          cgstAmount: '3427.20',
          sgstAmount: '3427.20',
          igstAmount: '0.00',
          totalAmount: '44934.40',
        },
        {
          id: 2,
          invoiceId: 1,
          description: 'POP Ceiling & Site Fascia Work (199 sq.ft after ₹1,436 discount)',
          hsnSac: '9954',
          quantity: '199.00',
          unit: 'sq.ft',
          rate: '90.05',
          taxableValue: '17920.00',
          gstRate: '18.00',
          cgstAmount: '1612.80',
          sgstAmount: '1612.80',
          igstAmount: '0.00',
          totalAmount: '21145.60',
        },
      ],
    },
    {
      id: 2,
      uid: 'nrd_owner_uid',
      invoiceNumber: 'NRD/26-27/INV-002',
      invoiceDate: todayStr,
      dueDate: '2026-10-25',
      customerId: 2,
      projectId: 2,
      quotationId: null,
      measurementId: null,
      customerGstin: '27AAHCS9102K1Z8',
      placeOfSupply: 'Maharashtra (27)',
      isInterState: false,
      subtotal: '85000.00',
      discount: '0.00',
      taxableValue: '85000.00',
      gstRate: '18.00',
      cgstAmount: '7650.00',
      sgstAmount: '7650.00',
      igstAmount: '0.00',
      totalGst: '15300.00',
      grandTotal: '100300.00',
      amountPaid: '100300.00',
      balanceDue: '0.00',
      amountInWords: amountToIndianWords(100300),
      status: 'Paid',
      isFinalized: true,
      notes: 'Phase 1 Showroom Saint-Gobain Gypsum Board ceiling completed & settled.',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      items: [
        {
          id: 3,
          invoiceId: 2,
          description:
            'Saint-Gobain Gyproc 12.5mm False Ceiling with Heavy GI Grid (1000 sq.ft)',
          hsnSac: '9954',
          quantity: '1000.00',
          unit: 'sq.ft',
          rate: '85.00',
          taxableValue: '85000.00',
          gstRate: '18.00',
          cgstAmount: '7650.00',
          sgstAmount: '7650.00',
          igstAmount: '0.00',
          totalAmount: '100300.00',
        },
      ],
    },
  ],
  payments: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      receiptNumber: 'NRD/26-27/RCP-001',
      paymentDate: todayStr,
      invoiceId: 1,
      customerId: 1,
      projectId: 1,
      amount: '40000.00',
      paymentMethod: 'UPI',
      referenceNumber: 'UPI/427719283412/HDFC',
      notes: 'Advance + 1st stage payment for Deshmukh Duplex PVC & POP work',
      createdBy: 'Admin',
    },
    {
      id: 2,
      uid: 'nrd_owner_uid',
      receiptNumber: 'NRD/26-27/RCP-002',
      paymentDate: todayStr,
      invoiceId: 2,
      customerId: 2,
      projectId: 2,
      amount: '100300.00',
      paymentMethod: 'Bank Transfer',
      referenceNumber: 'NEFT/HDFCN520261003991',
      notes: 'Full settlement against Invoice NRD/26-27/INV-002',
      createdBy: 'Admin',
    },
  ],
  expenses: [
    {
      id: 1,
      uid: 'nrd_owner_uid',
      expenseDate: todayStr,
      category: 'Material Purchase',
      projectId: 1,
      vendorName: 'Royal Plast Distributors, Timber Market',
      amount: '24500.00',
      paymentMethod: 'Bank Transfer',
      referenceNumber: 'BILL-RP-882',
      notes: 'PVC Panels 10"x10ft & GI Channels for Deshmukh Duplex site',
      createdBy: 'Admin',
    },
    {
      id: 2,
      uid: 'nrd_owner_uid',
      expenseDate: todayStr,
      category: 'Site Labour',
      projectId: 1,
      vendorName: 'Imran Shaikh & POP Contractor Team',
      amount: '14200.00',
      paymentMethod: 'UPI',
      referenceNumber: 'UPI-LAB-109',
      notes: 'Site framing & PVC panel fitting labour payout',
      createdBy: 'Admin',
    },
    {
      id: 3,
      uid: 'nrd_owner_uid',
      expenseDate: todayStr,
      category: 'Material Purchase',
      projectId: 2,
      vendorName: 'Pune Gypsum & Hardware Mart',
      amount: '41000.00',
      paymentMethod: 'Bank Transfer',
      referenceNumber: 'PGHM-1920',
      notes: 'Saint-Gobain Gyproc boards, GI channels & drywall screws',
      createdBy: 'Admin',
    },
    {
      id: 4,
      uid: 'nrd_owner_uid',
      expenseDate: todayStr,
      category: 'Site Labour',
      projectId: 2,
      vendorName: 'Sandeep Jadhav Gypsum Crew',
      amount: '19500.00',
      paymentMethod: 'Cash',
      referenceNumber: 'VOUCH-44',
      notes: 'Showroom gypsum boarding and jointing compound finishing',
      createdBy: 'Admin',
    },
  ],
  attachments: [],
  settings: [],
};
